# -*- coding: utf-8 -*-
"""github-colab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/ndhcuong/pythonbasics/blob/master/github_colab.ipynb

**Đây là chương trình đầu tiên**
"""

print("Hello Github & Colab")